services:

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hotel_net

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./auth_service:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hotel_net

  hotel_service:
    build:
      context: ./hotel_service
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hotel_service:/app
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hotel_net

  booking_service:
    build:
      context: ./booking_service
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./booking_service:/app
    expose:
      - "8002"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hotel_net

  chat_service:
    build:
      context: ./chat_service
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8004 chat_service.asgi:application
    expose:
      - "8004"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: chat_service.settings
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hotel_net

  post_service:
    build:
      context: ./post_service
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - ./post_service:/app
    expose:
      - "8003"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: post_service.settings
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hotel_net

  api_gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./gateway:/app
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: gateway.settings
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DJANGO_DEBUG}
    depends_on:
      - auth_service
      - hotel_service
      - booking_service
      - chat_service
    networks:
      - hotel_net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_gateway
      - chat_service
    networks:
      - hotel_net

volumes:
  mysql_data:

networks:
  hotel_net:
    driver: bridge